$(document).ready(function(){
    setTimeout(function(){
        $("#1").removeClass("invisible")
        $("#1").addClass("animate__animated")
        $("#1").addClass("animate__slideInUp")
    },200)
    setTimeout(function(){
        $("#2").removeClass("invisible")
        $("#2").addClass("animate__animated")
        $("#2").addClass("animate__slideInUp")
    },400)
    setTimeout(function(){
        $("#3").removeClass("invisible")
        $("#3").addClass("animate__animated")
        $("#3").addClass("animate__slideInUp")
    },600)
    setTimeout(function(){
        $("#4").removeClass("invisible")
        $("#4").addClass("animate__animated")
        $("#4").addClass("animate__slideInUp")
    },800)
    setTimeout(function(){
        $("#5").removeClass("invisible")
        $("#5").addClass("animate__animated")
        $("#5").addClass("animate__slideInUp")
    },1000)
    setTimeout(function(){
        $("#6").removeClass("invisible")
        $("#6").addClass("animate__animated")
        $("#6").addClass("animate__slideInUp")
    },1200)
    setTimeout(function(){
        $("#7").removeClass("invisible")
        $("#7").addClass("animate__animated")
        $("#7").addClass("animate__slideInUp")
    },1400)
});